md "../../downloads/Reddit/protestfreakout"
md "../../downloads/Reddit/protestfreakout/Imgur Albums"
cd "../../downloads/Reddit/protestfreakout/Imgur Albums"
gallery-dl "https://imgur.com/a/Vu1G6cz"
gallery-dl "https://imgur.com/a/LqpBP94"
gallery-dl "https://imgur.com/a/PeiucK3"
gallery-dl "https://imgur.com/a/VQ5q4VQ"
gallery-dl "https://imgur.com/a/Cf2f8sB"
gallery-dl "https://imgur.com/a/qjbgmWf"
