md "../../../downloads/Twitter/flashhardcor
md "../../../downloads/Twitter/flashhardcor/images"
curl -k "https://pbs.twimg.com/media/EvMeGLNUUAAF-p3.jpg" -o "../../../downloads/Twitter/flashhardcor/images/EvMeGLNUUAAF-p3.jpg"
curl -k "https://pbs.twimg.com/media/En3l4H1UcAAQdKA.jpg" -o "../../../downloads/Twitter/flashhardcor/images/En3l4H1UcAAQdKA.jpg"
curl -k "https://pbs.twimg.com/media/EjXJBNGVcAAVcH8.jpg" -o "../../../downloads/Twitter/flashhardcor/images/EjXJBNGVcAAVcH8.jpg"
curl -k "https://pbs.twimg.com/media/EjIE2yRU8AENSlW.jpg" -o "../../../downloads/Twitter/flashhardcor/images/EjIE2yRU8AENSlW.jpg"
curl -k "https://pbs.twimg.com/media/EjDltwgUcAIOaO0.jpg" -o "../../../downloads/Twitter/flashhardcor/images/EjDltwgUcAIOaO0.jpg"
curl -k "https://pbs.twimg.com/media/EhJCp0pUcAA5fuH.jpg" -o "../../../downloads/Twitter/flashhardcor/images/EhJCp0pUcAA5fuH.jpg"
curl -k "https://pbs.twimg.com/media/EhIIiO6UwAAp7-a.jpg" -o "../../../downloads/Twitter/flashhardcor/images/EhIIiO6UwAAp7-a.jpg"
curl -k "https://pbs.twimg.com/media/EgnYxeKUYAAPrXS.jpg" -o "../../../downloads/Twitter/flashhardcor/images/EgnYxeKUYAAPrXS.jpg"
curl -k "https://pbs.twimg.com/media/Ee90p4yU8AA_ANo.jpg" -o "../../../downloads/Twitter/flashhardcor/images/Ee90p4yU8AA_ANo.jpg"
curl -k "https://pbs.twimg.com/media/EdmPzCJU8AEUMxe.jpg" -o "../../../downloads/Twitter/flashhardcor/images/EdmPzCJU8AEUMxe.jpg"
curl -k "https://pbs.twimg.com/media/EdgPk8zUMAAGwuE.jpg" -o "../../../downloads/Twitter/flashhardcor/images/EdgPk8zUMAAGwuE.jpg"
curl -k "https://pbs.twimg.com/media/EdcVu1nUEAA-GAq.jpg" -o "../../../downloads/Twitter/flashhardcor/images/EdcVu1nUEAA-GAq.jpg"
curl -k "https://pbs.twimg.com/media/EdbKm9fVcAA8--N.jpg" -o "../../../downloads/Twitter/flashhardcor/images/EdbKm9fVcAA8--N.jpg"
curl -k "https://pbs.twimg.com/media/EdRgy5KVcAAXh1N.png" -o "../../../downloads/Twitter/flashhardcor/images/EdRgy5KVcAAXh1N.png"
curl -k "https://pbs.twimg.com/media/EdA322CUYAE4RCd.jpg" -o "../../../downloads/Twitter/flashhardcor/images/EdA322CUYAE4RCd.jpg"
curl -k "https://pbs.twimg.com/media/Ec7mU3AU4AA9EEB.jpg" -o "../../../downloads/Twitter/flashhardcor/images/Ec7mU3AU4AA9EEB.jpg"
