md "../../../downloads/Twitter/cdsupriyadi
md "../../../downloads/Twitter/cdsupriyadi/images"
curl -k "https://pbs.twimg.com/media/Eu9m54EVoAEpAtf.jpg" -o "../../../downloads/Twitter/cdsupriyadi/images/Eu9m54EVoAEpAtf.jpg"
curl -k "https://pbs.twimg.com/media/EtDjUunUYIkC9jL.jpg" -o "../../../downloads/Twitter/cdsupriyadi/images/EtDjUunUYIkC9jL.jpg"
curl -k "https://pbs.twimg.com/media/EtDjVRVUUAA7xZs.jpg" -o "../../../downloads/Twitter/cdsupriyadi/images/EtDjVRVUUAA7xZs.jpg"
curl -k "https://pbs.twimg.com/media/EsjTPiCU4AA6kTq.jpg" -o "../../../downloads/Twitter/cdsupriyadi/images/EsjTPiCU4AA6kTq.jpg"
curl -k "https://pbs.twimg.com/media/EsjPpBSVEAAX2nj.jpg" -o "../../../downloads/Twitter/cdsupriyadi/images/EsjPpBSVEAAX2nj.jpg"
curl -k "https://pbs.twimg.com/media/EsjPpCGVcAsMSkK.jpg" -o "../../../downloads/Twitter/cdsupriyadi/images/EsjPpCGVcAsMSkK.jpg"
curl -k "https://pbs.twimg.com/media/EsjPpBTU4AEVMrE.jpg" -o "../../../downloads/Twitter/cdsupriyadi/images/EsjPpBTU4AEVMrE.jpg"
curl -k "https://pbs.twimg.com/media/EsZjkoFVEAAT58-.jpg" -o "../../../downloads/Twitter/cdsupriyadi/images/EsZjkoFVEAAT58-.jpg"
curl -k "https://pbs.twimg.com/media/EsZcZUrUcAA3AK4.jpg" -o "../../../downloads/Twitter/cdsupriyadi/images/EsZcZUrUcAA3AK4.jpg"
curl -k "https://pbs.twimg.com/media/EsZcj35UYAEqn7R.jpg" -o "../../../downloads/Twitter/cdsupriyadi/images/EsZcj35UYAEqn7R.jpg"
curl -k "https://pbs.twimg.com/media/EsZjkoEUcAAk-U6.jpg" -o "../../../downloads/Twitter/cdsupriyadi/images/EsZjkoEUcAAk-U6.jpg"
curl -k "https://pbs.twimg.com/media/EsYhxJ_VoAA4Pd7.jpg" -o "../../../downloads/Twitter/cdsupriyadi/images/EsYhxJ_VoAA4Pd7.jpg"
curl -k "https://pbs.twimg.com/media/EsDcJcBVcAAX3lL.jpg" -o "../../../downloads/Twitter/cdsupriyadi/images/EsDcJcBVcAAX3lL.jpg"
curl -k "https://pbs.twimg.com/media/Em-VWwKVoAAlEp4.jpg" -o "../../../downloads/Twitter/cdsupriyadi/images/Em-VWwKVoAAlEp4.jpg"
curl -k "https://pbs.twimg.com/media/EhllFN_XkAI8e1i.jpg" -o "../../../downloads/Twitter/cdsupriyadi/images/EhllFN_XkAI8e1i.jpg"
