md "../../../downloads/Twitter/joannpdx
md "../../../downloads/Twitter/joannpdx/images"
curl -k "https://pbs.twimg.com/media/ErFu981UUAM4L5-.png" -o "../../../downloads/Twitter/joannpdx/images/ErFu981UUAM4L5-.png"
curl -k "https://pbs.twimg.com/media/Ek0rhCHVkAM7vJX.png" -o "../../../downloads/Twitter/joannpdx/images/Ek0rhCHVkAM7vJX.png"
curl -k "https://pbs.twimg.com/media/EkKiesrUcAAz8nf.png" -o "../../../downloads/Twitter/joannpdx/images/EkKiesrUcAAz8nf.png"
curl -k "https://pbs.twimg.com/media/Ef0dHnsVAAAux_D.png" -o "../../../downloads/Twitter/joannpdx/images/Ef0dHnsVAAAux_D.png"
curl -k "https://pbs.twimg.com/media/Ef0dQQ1UEAE001q.png" -o "../../../downloads/Twitter/joannpdx/images/Ef0dQQ1UEAE001q.png"
curl -k "https://pbs.twimg.com/media/Ec_4W0TUMAA3PKH.jpg" -o "../../../downloads/Twitter/joannpdx/images/Ec_4W0TUMAA3PKH.jpg"
curl -k "https://pbs.twimg.com/media/Eb4hCdBVcAIPJic.jpg" -o "../../../downloads/Twitter/joannpdx/images/Eb4hCdBVcAIPJic.jpg"
curl -k "https://pbs.twimg.com/media/Eb4hCdBUYAAIrHG.jpg" -o "../../../downloads/Twitter/joannpdx/images/Eb4hCdBUYAAIrHG.jpg"
curl -k "https://pbs.twimg.com/media/Ea5ZpPJU8AArHgX.jpg" -o "../../../downloads/Twitter/joannpdx/images/Ea5ZpPJU8AArHgX.jpg"
curl -k "https://pbs.twimg.com/media/EaRkSiqUYAATAUn.png" -o "../../../downloads/Twitter/joannpdx/images/EaRkSiqUYAATAUn.png"
curl -k "https://pbs.twimg.com/media/EaRkSirUcAA7TDq.png" -o "../../../downloads/Twitter/joannpdx/images/EaRkSirUcAA7TDq.png"
curl -k "https://pbs.twimg.com/media/EZuHV6hUEAAUiDE.jpg" -o "../../../downloads/Twitter/joannpdx/images/EZuHV6hUEAAUiDE.jpg"
curl -k "https://pbs.twimg.com/media/EYgI4IaU8AArcEc.png" -o "../../../downloads/Twitter/joannpdx/images/EYgI4IaU8AArcEc.png"
curl -k "https://pbs.twimg.com/media/EXNQqMvWkAUx-y-.jpg" -o "../../../downloads/Twitter/joannpdx/images/EXNQqMvWkAUx-y-.jpg"
