md "../../../downloads/Twitter/tedwheeler
md "../../../downloads/Twitter/tedwheeler/images"
curl -k "https://pbs.twimg.com/media/EuEcMvQVcAA6DpH.jpg" -o "../../../downloads/Twitter/tedwheeler/images/EuEcMvQVcAA6DpH.jpg"
curl -k "https://pbs.twimg.com/media/EtZvxYeVkAUYOCf.png" -o "../../../downloads/Twitter/tedwheeler/images/EtZvxYeVkAUYOCf.png"
curl -k "https://pbs.twimg.com/media/EtZvVzpVkAA3jqf.png" -o "../../../downloads/Twitter/tedwheeler/images/EtZvVzpVkAA3jqf.png"
curl -k "https://pbs.twimg.com/media/Eq515UXWMAE5lz7.png" -o "../../../downloads/Twitter/tedwheeler/images/Eq515UXWMAE5lz7.png"
curl -k "https://pbs.twimg.com/media/Ep4a28DUYAMq1vy.jpg" -o "../../../downloads/Twitter/tedwheeler/images/Ep4a28DUYAMq1vy.jpg"
curl -k "https://pbs.twimg.com/media/EmPBM1lXEAA05gB.jpg" -o "../../../downloads/Twitter/tedwheeler/images/EmPBM1lXEAA05gB.jpg"
curl -k "https://pbs.twimg.com/media/EmKe45IVoAEciqr.jpg" -o "../../../downloads/Twitter/tedwheeler/images/EmKe45IVoAEciqr.jpg"
curl -k "https://pbs.twimg.com/media/EjavIfmUYAYgSaz.jpg" -o "../../../downloads/Twitter/tedwheeler/images/EjavIfmUYAYgSaz.jpg"
curl -k "https://pbs.twimg.com/media/EiVT7osU4AAj-7s.jpg" -o "../../../downloads/Twitter/tedwheeler/images/EiVT7osU4AAj-7s.jpg"
curl -k "https://pbs.twimg.com/media/Ec_FL1QU0AEQNjX.jpg" -o "../../../downloads/Twitter/tedwheeler/images/Ec_FL1QU0AEQNjX.jpg"
curl -k "https://pbs.twimg.com/media/EcWgjWTVcAADpQO.jpg" -o "../../../downloads/Twitter/tedwheeler/images/EcWgjWTVcAADpQO.jpg"
curl -k "https://pbs.twimg.com/media/Ebu40FZU8AAJiLh.jpg" -o "../../../downloads/Twitter/tedwheeler/images/Ebu40FZU8AAJiLh.jpg"
curl -k "https://pbs.twimg.com/media/Ea5HQJiUcAENR8b.jpg" -o "../../../downloads/Twitter/tedwheeler/images/Ea5HQJiUcAENR8b.jpg"
curl -k "https://pbs.twimg.com/media/EZTi7VKUwAAH8rm.jpg" -o "../../../downloads/Twitter/tedwheeler/images/EZTi7VKUwAAH8rm.jpg"
curl -k "https://pbs.twimg.com/media/EXsbydVVAAMhoYK.jpg" -o "../../../downloads/Twitter/tedwheeler/images/EXsbydVVAAMhoYK.jpg"
curl -k "https://pbs.twimg.com/media/EXdCNIDU0AABjr-.jpg" -o "../../../downloads/Twitter/tedwheeler/images/EXdCNIDU0AABjr-.jpg"
