md "../../../downloads/Reddit/protestfreakout"
md "../../../downloads/Reddit/protestfreakout/images"
curl -k "https://i.imgur.com/hUN3RRt.jpg" -o "../../../downloads/Reddit/protestfreakout/images/hUN3RRt.jpg"
curl -k "https://i.imgur.com/8ONqd5k.jpg" -o "../../../downloads/Reddit/protestfreakout/images/8ONqd5k.jpg"
curl -k "https://i.imgur.com/jFNVQ7O.jpg" -o "../../../downloads/Reddit/protestfreakout/images/jFNVQ7O.jpg"
curl -k "https://i.imgur.com/rrXALA4.jpg" -o "../../../downloads/Reddit/protestfreakout/images/rrXALA4.jpg"
curl -k "https://i.imgur.com/tSsaO91.jpg" -o "../../../downloads/Reddit/protestfreakout/images/tSsaO91.jpg"
