md "../../../downloads/Reddit/EnoughAntifaSpam"
md "../../../downloads/Reddit/EnoughAntifaSpam/Reddit Videos"
youtube-dl "https://v.redd.it/ox8j3ln2yht71" --config-location "../../youtube-dl.conf" -o "../../../downloads/Reddit/EnoughAntifaSpam/Reddit Videos/%%(id)s.%%(ext)s"
youtube-dl "https://v.redd.it/7rp9laj3ogd71" --config-location "../../youtube-dl.conf" -o "../../../downloads/Reddit/EnoughAntifaSpam/Reddit Videos/%%(id)s.%%(ext)s"
youtube-dl "https://v.redd.it/5xgiqo3b3e971" --config-location "../../youtube-dl.conf" -o "../../../downloads/Reddit/EnoughAntifaSpam/Reddit Videos/%%(id)s.%%(ext)s"
youtube-dl "https://v.redd.it/gh0bl492o7271" --config-location "../../youtube-dl.conf" -o "../../../downloads/Reddit/EnoughAntifaSpam/Reddit Videos/%%(id)s.%%(ext)s"
youtube-dl "https://v.redd.it/1jqmt0rn9wi61" --config-location "../../youtube-dl.conf" -o "../../../downloads/Reddit/EnoughAntifaSpam/Reddit Videos/%%(id)s.%%(ext)s"
youtube-dl "https://v.redd.it/aima4ulxqvi61" --config-location "../../youtube-dl.conf" -o "../../../downloads/Reddit/EnoughAntifaSpam/Reddit Videos/%%(id)s.%%(ext)s"
youtube-dl "https://v.redd.it/d1qnrg7rknz51" --config-location "../../youtube-dl.conf" -o "../../../downloads/Reddit/EnoughAntifaSpam/Reddit Videos/%%(id)s.%%(ext)s"
youtube-dl "https://v.redd.it/ukx2s6tvbbe51" --config-location "../../youtube-dl.conf" -o "../../../downloads/Reddit/EnoughAntifaSpam/Reddit Videos/%%(id)s.%%(ext)s"
