md "../../../downloads/Reddit/Portland"
md "../../../downloads/Reddit/Portland/Vimeo"
youtube-dl "https://vimeo.com/533761329" --config-location "../../youtube-dl.conf" -o "../../../downloads/Reddit/Portland/Vimeo/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://vimeo.com/518834778?ref=em-share" --config-location "../../youtube-dl.conf" -o "../../../downloads/Reddit/Portland/Vimeo/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://vimeo.com/19607481" --config-location "../../youtube-dl.conf" -o "../../../downloads/Reddit/Portland/Vimeo/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://vimeo.com/505416261?ref=em-share" --config-location "../../youtube-dl.conf" -o "../../../downloads/Reddit/Portland/Vimeo/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://vimeo.com/505046647" --config-location "../../youtube-dl.conf" -o "../../../downloads/Reddit/Portland/Vimeo/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://vimeo.com/421190821/3759c66dcf?fbclid=IwAR2P_lv1E86P_aUinFW9IlZf_G3gaxyeiY1AbkdUKiZF6QwnH8JtdF0ElGA" --config-location "../../youtube-dl.conf" -o "../../../downloads/Reddit/Portland/Vimeo/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://vimeo.com/486103804" --config-location "../../youtube-dl.conf" -o "../../../downloads/Reddit/Portland/Vimeo/%%(title)s (%%(id)s).%%(ext)s"
