md "../../../downloads/Reddit/InsaneProtestors"
md "../../../downloads/Reddit/InsaneProtestors/Imgur Albums"
cd "../../../downloads/Reddit/InsaneProtestors/Imgur Albums"
gallery-dl "https://imgur.com/a/zP3Twon"
gallery-dl "https://imgur.com/a/arJZlUa"
gallery-dl "https://imgur.com/a/pYi7vTI"
