md "../../../downloads/Reddit/protestfreakout"
md "../../../downloads/Reddit/protestfreakout/images"
curl -k "https://i.redd.it/1r0ck3zwtxb71.jpg" -o "../../../downloads/Reddit/protestfreakout/images/1r0ck3zwtxb71.jpg"
curl -k "https://i.redd.it/1l5dsjmnqga71.jpg" -o "../../../downloads/Reddit/protestfreakout/images/1l5dsjmnqga71.jpg"
curl -k "https://i.redd.it/t7nqsx21en371.png" -o "../../../downloads/Reddit/protestfreakout/images/t7nqsx21en371.png"
curl -k "https://i.redd.it/xswo1vjn7a071.png" -o "../../../downloads/Reddit/protestfreakout/images/xswo1vjn7a071.png"
curl -k "https://i.redd.it/ouso3k4sb9g61.jpg" -o "../../../downloads/Reddit/protestfreakout/images/ouso3k4sb9g61.jpg"
curl -k "https://i.redd.it/a8jvrdnr6gf61.jpg" -o "../../../downloads/Reddit/protestfreakout/images/a8jvrdnr6gf61.jpg"
curl -k "https://i.redd.it/4l2aas8libf61.jpg" -o "../../../downloads/Reddit/protestfreakout/images/4l2aas8libf61.jpg"
curl -k "https://i.redd.it/lg5athk78ma61.jpg" -o "../../../downloads/Reddit/protestfreakout/images/lg5athk78ma61.jpg"
curl -k "https://i.redd.it/fsbev285h2m51.jpg" -o "../../../downloads/Reddit/protestfreakout/images/fsbev285h2m51.jpg"
curl -k "https://i.redd.it/k9vssa4tkii51.jpg" -o "../../../downloads/Reddit/protestfreakout/images/k9vssa4tkii51.jpg"
curl -k "https://i.redd.it/c1vpj3n1oci51.jpg" -o "../../../downloads/Reddit/protestfreakout/images/c1vpj3n1oci51.jpg"
curl -k "https://i.redd.it/4qnjrq5xwtb51.jpg" -o "../../../downloads/Reddit/protestfreakout/images/4qnjrq5xwtb51.jpg"
curl -k "https://i.redd.it/aa79808qfz751.jpg" -o "../../../downloads/Reddit/protestfreakout/images/aa79808qfz751.jpg"
curl -k "https://i.redd.it/cuj091m2te351.jpg" -o "../../../downloads/Reddit/protestfreakout/images/cuj091m2te351.jpg"
curl -k "https://i.redd.it/f7l5ifofse351.jpg" -o "../../../downloads/Reddit/protestfreakout/images/f7l5ifofse351.jpg"
curl -k "https://i.redd.it/h9fhzf4jy6251.jpg" -o "../../../downloads/Reddit/protestfreakout/images/h9fhzf4jy6251.jpg"
