md "../../../downloads/YouTube"
youtube-dl "https://www.youtube.com/watch?v=8U_Ha-6haBg" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/The Daily Signal/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=lvqbvwi4QT4" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/The Daily Signal/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=GhPEXvLRD1Q" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/The Daily Signal/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=WjiqS8gPPB0" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/The Daily Signal/%%(title)s (%%(id)s).%%(ext)s"
