md "../../../downloads/YouTube"
youtube-dl "https://www.youtube.com/watch?v=-n1pHHNYH-E" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/JRE Clips/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=jCHfBfO_oLk" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/JRE Clips/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=G8QN6X2eY4k" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/JRE Clips/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=ozx6JjT75a4" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/JRE Clips/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=p4_V5Oz7RZs" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/JRE Clips/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=7fup7Fcs7UM" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/JRE Clips/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=xdTS2ljRYEE" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/JRE Clips/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=Jyb2JhysVr4" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/JRE Clips/%%(title)s (%%(id)s).%%(ext)s"
