md "../../../downloads/YouTube"
youtube-dl "https://www.youtube.com/watch?v=jQ9-vdf59AI" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/Perseus999/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=2wgXc5atTTc" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/Perseus999/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=4KXHzvA13as" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/Perseus999/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=nOAp_LtzbPk" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/Perseus999/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=WRUTdjbDl6E" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/Perseus999/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=KilUutQHbLs" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/Perseus999/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=7zHqsqPFqcQ" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/Perseus999/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=QG9ebjVIivA" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/Perseus999/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=OFTNrUD9Xaw" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/Perseus999/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=WxQmCJGLnyQ" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/Perseus999/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=KXagEtsrIP0" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/Perseus999/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=DW-n4P-l2Wk" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/Perseus999/%%(title)s (%%(id)s).%%(ext)s"
youtube-dl "https://www.youtube.com/watch?v=2gulGaNLy_U" --config-location "../../youtube-dl.conf" -o "../../../downloads/YouTube/Perseus999/%%(title)s (%%(id)s).%%(ext)s"
