md "../../downloads/Twitter/Clypian
md "../../downloads/Twitter/Clypian/images"
curl -k "https://pbs.twimg.com/media/Epdl6QlUcAAtNED.jpg" -o "../../downloads/Twitter/Clypian/images/Epdl6QlUcAAtNED.jpg"
curl -k "https://pbs.twimg.com/media/EdWKP_RVcAAV9PW.jpg" -o "../../downloads/Twitter/Clypian/images/EdWKP_RVcAAV9PW.jpg"
curl -k "https://pbs.twimg.com/media/EdV1EitUEAEyEvZ.jpg" -o "../../downloads/Twitter/Clypian/images/EdV1EitUEAEyEvZ.jpg"
curl -k "https://pbs.twimg.com/media/EdVzRTvU8AYYWpy.jpg" -o "../../downloads/Twitter/Clypian/images/EdVzRTvU8AYYWpy.jpg"
curl -k "https://pbs.twimg.com/media/EdRORe5VcAAbdES.jpg" -o "../../downloads/Twitter/Clypian/images/EdRORe5VcAAbdES.jpg"
curl -k "https://pbs.twimg.com/media/EY6l07cUEAAO59k.jpg" -o "../../downloads/Twitter/Clypian/images/EY6l07cUEAAO59k.jpg"
curl -k "https://pbs.twimg.com/media/EYT49jIUYAAQhuQ.jpg" -o "../../downloads/Twitter/Clypian/images/EYT49jIUYAAQhuQ.jpg"
curl -k "https://pbs.twimg.com/media/EXxHVvxUwAAj91W.jpg" -o "../../downloads/Twitter/Clypian/images/EXxHVvxUwAAj91W.jpg"
curl -k "https://pbs.twimg.com/media/EXxHVvyUYAAgOYC.jpg" -o "../../downloads/Twitter/Clypian/images/EXxHVvyUYAAgOYC.jpg"
curl -k "https://pbs.twimg.com/media/EXxHV4tVcAIvftV.jpg" -o "../../downloads/Twitter/Clypian/images/EXxHV4tVcAIvftV.jpg"
curl -k "https://pbs.twimg.com/media/EXqzu0NU0AEUta9.jpg" -o "../../downloads/Twitter/Clypian/images/EXqzu0NU0AEUta9.jpg"
curl -k "https://pbs.twimg.com/media/EXIjeeIU8AAw_mO.jpg" -o "../../downloads/Twitter/Clypian/images/EXIjeeIU8AAw_mO.jpg"
