md "../../downloads/Twitter/byaliceyin
md "../../downloads/Twitter/byaliceyin/images"
curl -k "https://pbs.twimg.com/media/EwXLURzWUAM83nq.jpg" -o "../../downloads/Twitter/byaliceyin/images/EwXLURzWUAM83nq.jpg"
curl -k "https://pbs.twimg.com/media/EvQ8MUPXYAAn1DK.jpg" -o "../../downloads/Twitter/byaliceyin/images/EvQ8MUPXYAAn1DK.jpg"
curl -k "https://pbs.twimg.com/media/EvQZwgGXIAIkvtF.jpg" -o "../../downloads/Twitter/byaliceyin/images/EvQZwgGXIAIkvtF.jpg"
curl -k "https://pbs.twimg.com/media/EuhvkJLWQAIJq57.jpg" -o "../../downloads/Twitter/byaliceyin/images/EuhvkJLWQAIJq57.jpg"
curl -k "https://pbs.twimg.com/media/ErE59XXUcAEP2Sn.jpg" -o "../../downloads/Twitter/byaliceyin/images/ErE59XXUcAEP2Sn.jpg"
curl -k "https://pbs.twimg.com/media/EpdDK1QXUAQoC_a.jpg" -o "../../downloads/Twitter/byaliceyin/images/EpdDK1QXUAQoC_a.jpg"
curl -k "https://pbs.twimg.com/media/EjwlW9pWoAM4yvt.jpg" -o "../../downloads/Twitter/byaliceyin/images/EjwlW9pWoAM4yvt.jpg"
curl -k "https://pbs.twimg.com/media/EjwlW9pXkAAo9gZ.jpg" -o "../../downloads/Twitter/byaliceyin/images/EjwlW9pXkAAo9gZ.jpg"
curl -k "https://pbs.twimg.com/media/Ejcu19MWAAA29iE.jpg" -o "../../downloads/Twitter/byaliceyin/images/Ejcu19MWAAA29iE.jpg"
curl -k "https://pbs.twimg.com/media/EiH5tVTXgAIxvyd.jpg" -o "../../downloads/Twitter/byaliceyin/images/EiH5tVTXgAIxvyd.jpg"
curl -k "https://pbs.twimg.com/media/EgYzzNPWsAUFXjl.jpg" -o "../../downloads/Twitter/byaliceyin/images/EgYzzNPWsAUFXjl.jpg"
curl -k "https://pbs.twimg.com/media/EfqKTT8WsAg4zLq.jpg" -o "../../downloads/Twitter/byaliceyin/images/EfqKTT8WsAg4zLq.jpg"
curl -k "https://pbs.twimg.com/media/EfqKTT-WAAEiPF5.jpg" -o "../../downloads/Twitter/byaliceyin/images/EfqKTT-WAAEiPF5.jpg"
curl -k "https://pbs.twimg.com/media/EdKy1jAXoAYFFtf.jpg" -o "../../downloads/Twitter/byaliceyin/images/EdKy1jAXoAYFFtf.jpg"
curl -k "https://pbs.twimg.com/media/EabWTABWsAAo6Qm.jpg" -o "../../downloads/Twitter/byaliceyin/images/EabWTABWsAAo6Qm.jpg"
curl -k "https://pbs.twimg.com/media/EabIJjGX0AAni7D.jpg" -o "../../downloads/Twitter/byaliceyin/images/EabIJjGX0AAni7D.jpg"
curl -k "https://pbs.twimg.com/media/EaayPngXgAED5kD.jpg" -o "../../downloads/Twitter/byaliceyin/images/EaayPngXgAED5kD.jpg"
curl -k "https://pbs.twimg.com/media/EaQ3d0OXYAAtC50.jpg" -o "../../downloads/Twitter/byaliceyin/images/EaQ3d0OXYAAtC50.jpg"
curl -k "https://pbs.twimg.com/media/EaPabjeX0AcPuq2.jpg" -o "../../downloads/Twitter/byaliceyin/images/EaPabjeX0AcPuq2.jpg"
curl -k "https://pbs.twimg.com/media/EaPWAJgX0AAf7BA.jpg" -o "../../downloads/Twitter/byaliceyin/images/EaPWAJgX0AAf7BA.jpg"
curl -k "https://pbs.twimg.com/media/EYu_6KJX0AAjeWW.jpg" -o "../../downloads/Twitter/byaliceyin/images/EYu_6KJX0AAjeWW.jpg"
curl -k "https://pbs.twimg.com/media/EYTcdcKWkAMC-Cf.jpg" -o "../../downloads/Twitter/byaliceyin/images/EYTcdcKWkAMC-Cf.jpg"
