md "../../downloads/Twitter/crimethinc
md "../../downloads/Twitter/crimethinc/images"
curl -k "https://pbs.twimg.com/media/Eu4E1hQWQAADHV1.png" -o "../../downloads/Twitter/crimethinc/images/Eu4E1hQWQAADHV1.png"
curl -k "https://pbs.twimg.com/media/Es4b4fZXcAE-2r5.png" -o "../../downloads/Twitter/crimethinc/images/Es4b4fZXcAE-2r5.png"
curl -k "https://pbs.twimg.com/media/Ep_u4JhXIAA1OzR.jpg" -o "../../downloads/Twitter/crimethinc/images/Ep_u4JhXIAA1OzR.jpg"
curl -k "https://pbs.twimg.com/media/Ep-omy8WMAA5KuF.jpg" -o "../../downloads/Twitter/crimethinc/images/Ep-omy8WMAA5KuF.jpg"
curl -k "https://pbs.twimg.com/media/Ep35CYyXIAgdeAu.jpg" -o "../../downloads/Twitter/crimethinc/images/Ep35CYyXIAgdeAu.jpg"
curl -k "https://pbs.twimg.com/media/Ep35Ft2XMAU8nq1.jpg" -o "../../downloads/Twitter/crimethinc/images/Ep35Ft2XMAU8nq1.jpg"
curl -k "https://pbs.twimg.com/media/Ep35HQwW4AAqo_0.jpg" -o "../../downloads/Twitter/crimethinc/images/Ep35HQwW4AAqo_0.jpg"
curl -k "https://pbs.twimg.com/media/Ep35JY_XEAAobL4.jpg" -o "../../downloads/Twitter/crimethinc/images/Ep35JY_XEAAobL4.jpg"
curl -k "https://pbs.twimg.com/media/Ep35Mf-W4AAaX8v.jpg" -o "../../downloads/Twitter/crimethinc/images/Ep35Mf-W4AAaX8v.jpg"
curl -k "https://pbs.twimg.com/media/Ep347rUW8AI9uhC.jpg" -o "../../downloads/Twitter/crimethinc/images/Ep347rUW8AI9uhC.jpg"
curl -k "https://pbs.twimg.com/media/Enens8CWEAA5B_v.png" -o "../../downloads/Twitter/crimethinc/images/Enens8CWEAA5B_v.png"
curl -k "https://pbs.twimg.com/media/EnenoDKW8AUKiDK.png" -o "../../downloads/Twitter/crimethinc/images/EnenoDKW8AUKiDK.png"
curl -k "https://pbs.twimg.com/media/EnenO3lW4AAj6F2.png" -o "../../downloads/Twitter/crimethinc/images/EnenO3lW4AAj6F2.png"
curl -k "https://pbs.twimg.com/media/EnehLIyXMAE3LQk.png" -o "../../downloads/Twitter/crimethinc/images/EnehLIyXMAE3LQk.png"
curl -k "https://pbs.twimg.com/media/EnehGi5WMAI8R6a.png" -o "../../downloads/Twitter/crimethinc/images/EnehGi5WMAI8R6a.png"
curl -k "https://pbs.twimg.com/media/EnehAcQWEAMAKXw.png" -o "../../downloads/Twitter/crimethinc/images/EnehAcQWEAMAKXw.png"
curl -k "https://pbs.twimg.com/media/Eneg6JrW4AIuZwE.png" -o "../../downloads/Twitter/crimethinc/images/Eneg6JrW4AIuZwE.png"
curl -k "https://pbs.twimg.com/media/Eneg1XnW8AQnHCg.png" -o "../../downloads/Twitter/crimethinc/images/Eneg1XnW8AQnHCg.png"
curl -k "https://pbs.twimg.com/media/Enegs-WW4AAq2Uh.png" -o "../../downloads/Twitter/crimethinc/images/Enegs-WW4AAq2Uh.png"
curl -k "https://pbs.twimg.com/media/EnegAjsW8AA0A1k.png" -o "../../downloads/Twitter/crimethinc/images/EnegAjsW8AA0A1k.png"
curl -k "https://pbs.twimg.com/media/ElOBGakXIAA8RDl.png" -o "../../downloads/Twitter/crimethinc/images/ElOBGakXIAA8RDl.png"
curl -k "https://pbs.twimg.com/media/ElOBBOkXUAoug7u.png" -o "../../downloads/Twitter/crimethinc/images/ElOBBOkXUAoug7u.png"
curl -k "https://pbs.twimg.com/media/EiFTQ4DXcAAIq-T.png" -o "../../downloads/Twitter/crimethinc/images/EiFTQ4DXcAAIq-T.png"
curl -k "https://pbs.twimg.com/media/EZkuS1fX0AIGvw5.jpg" -o "../../downloads/Twitter/crimethinc/images/EZkuS1fX0AIGvw5.jpg"
curl -k "https://pbs.twimg.com/media/EZFme5oXgAAfzwk.png" -o "../../downloads/Twitter/crimethinc/images/EZFme5oXgAAfzwk.png"
